export const userConstants = {
  REGISTER: 'USERS_REGISTER',
  // REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  // REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN: 'USERS_LOGIN',
  // LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  // LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
  
  LOGOUT: 'USERS_LOGOUT',

  // GETALL_REQUEST: 'USERS_GETALL_REQUEST',
  // GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
  // GETALL_FAILURE: 'USERS_GETALL_FAILURE',

  DELETE: 'USERS_DELETE',
  // DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  // DELETE_FAILURE: 'USERS_DELETE_FAILURE'    
};
