export const ADD_ITEM_IN_CART = "ADD_ITEM_IN_CART";
export const SHOW_CART_DLG = "SHOW_CART_DLG";
export const DELETE_CHECKEDOUT_ITEM = "DELETE_CHECKEDOUT_ITEM";
export const TOGGLE_MENU = "TOGGLE_MENU";
export const UPDATE_CHECKEDOUT_ITEM_QUANTITY = "UPDATE_CHECKEDOUT_ITEM_QUANTITY";
export const SET_CHECKEDOUT_ITEMS = "SET_CHECKEDOUT_ITEMS";

export const LOGOUT = "LOGOUT";
export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";